#!/bin/sh
#
# Filter list for various ad servers. Makes your webbrowser open less
# connections.
#
# See the downloaded file itself for the copyright notice.
#

curl -s https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS > /etc/hosts.d/03-hosts.chefkoch

